name: GitHub Actions Usecases with All

on:
  push:
  pull_request:
    types: [opened, synchronized]
  workflow_dispatch:

# Workflow-level variables
env:
  MAVEN_TEST: "-Xmx1024m"
  BUILD_PROFILE_DEV: "release"

jobs:
  java-setup-single:
    name: Java Setup with Maven
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        include:
          - index: 0
            os: ubuntu-latest
            java: 17
          - index: 1
            os: ubuntu-latest
            java: 21
          - index: 2
            os: windows-latest
            java: 17
          - index: 3
            os: windows-latest
            java: 21

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Java ${{ matrix.java }}
        uses: actions/setup-java@v4.7.1
        with:
          java-version: ${{ matrix.java }}
          distribution: 'oracle'
         

      - name: Print Java Version
        run: java -version

      - name: Show Matrix Info
        run: |
          echo 'Running index ${{ matrix.index }}'
          echo 'OS: ${{ matrix.os }}, Java: ${{ matrix.java }}'
          echo 'BUILD_PROFILE: ${{ env.MAVEN_TEST }}'
          echo 'BUILD_PROFILE: ${{ vars.BUILD_PROFILE }}'
          echo 'BUILD_PROFILE: ${{ env.BUILD_PROFILE_DEV }}'
          echo 'BUILD_PROFILE: ${{ vars.MAVEN_OPTS}}'
          echo 'API_TOKEN: ${{ secrets.API_TOKEN }}'

    
