name: GitHub Actions Usecases with All

on:
  push:
  pull_request:
    types: [opened, synchronized]
  workflow_dispatch:

env:
  MAVEN_TEST: "-Xmx1024m"
  BUILD_PROFILE_DEV: "release"

jobs:
  java-setup-single:
    name: Java Setup with Maven
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        include:
          - index: 0
            os: ubuntu-latest
            java: 17
          - index: 1
            os: ubuntu-latest
            java: 21
          - index: 2
            os: windows-latest
            java: 17
          - index: 3
            os: windows-latest
            java: 21

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Java ${{ matrix.java }}
        uses: actions/setup-java@v4.7.1
        with:
          java-version: ${{ matrix.java }}
          distribution: 'oracle'

      - name: Print Java Version
        run: java -version

      - name: Show Matrix Info
        run: |
          echo "Running index ${{ matrix.index }}"
          echo "OS: ${{ matrix.os }}, Java: ${{ matrix.java }}"
          echo "BUILD_PROFILE: ${{ env.MAVEN_TEST }}"
          echo "BUILD_PROFILE_DEV: ${{ env.BUILD_PROFILE_DEV }}"
          echo "API_TOKEN: ${{ secrets.API_TOKEN }}"

  test:
    name: Run Tests
    needs: java-setup-single
    runs-on: windows-latest
    steps:
      - name: On Pull Request
        if: ${{ github.event_name == 'pull_request' && github.base_ref == 'main' }}
        run: echo 'Triggered by event ${{ github.event_name }}'
      - name: On Workflow dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo 'Triggered by event ${{ github.event_name }}'

  run-on-main-pr:
    needs: [java-setup-single, test]
    if: ${{ github.event_name == 'pull_request' && github.base_ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo Target Branch
        run: echo "This PR targets the main branch!"


    

    
