name : GitHub Context 
on :
  workflow_dispatch 
    jobs :
    githubcontext : 
      runs-on: ubuntu-latest
      steps :
        - name : print about GitHub Context
          run :
          -'|echo  test'
      
