name: SonarQube - Setup

on:
  workflow_dispatch:

jobs:
  sonarqube-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Token Presence
        run: |
          echo "Token length: ${#SONAR_TOKEN}"
        shell: bash
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@v5.0.0
        with:
          scannerVersion: '7.0.2.4839'
        
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Print SonarQube version
        run: sonar-scanner --version
