name: Variable Creation (ENV)

on:
  workflow_dispatch:

env:
  STATE: Ap  # Global environment variable

jobs:
  variables:
    runs-on: ubuntu-latest
    env:
      STATE: TG  # Job-level environment variable
    steps:
      - name: Print Environment Variables
        env:
          STATE: TS  # Step-level environment variable
        run: |
          echo 'ENV STATE: ${{env.STATE}}'
          echo 'VAR STATE: ${{vars.STATE}}'
          echo 'Job STATE: $STATE'

     
      
